config/routes.rb
LunchTracker::Application.routes.draw do
  resources :lunches

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
	
  attr_accessible :date, :food, :restaurant

  validates :food, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lunches }
    end
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
    @lunch = Lunch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lunch }
    end
  end

  # GET /lunches/new
  # GET /lunches/new.json
  def new
    @lunch = Lunch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lunch }
    end
  end

  # GET /lunches/1/edit
  def edit
    @lunch = Lunch.find(params[:id])
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(params[:lunch])

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render json: @lunch, status: :created, location: @lunch }
      else
        format.html { render action: "new" }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lunches/1
  # PUT /lunches/1.json
  def update
    @lunch = Lunch.find(params[:id])

    respond_to do |format|
      if @lunch.update_attributes(params[:lunch])
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch = Lunch.find(params[:id])
    @lunch.destroy

    respond_to do |format|
      format.html { redirect_to lunches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LunchTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lunches/_form.html.erb
<%= form_for(@lunch) do |f| %>
  <% if @lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% @lunch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :restaurant %><br />
    <%= f.text_field :restaurant %>
  </div>
  <div class="field">
    <%= f.label :food %><br />
    <%= f.text_field :food %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<h1>Listing lunches</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Restaurant</th>
    <th>Food</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lunches.each do |lunch| %>
  <tr>
    <td><%= lunch.date %></td>
    <td><%= lunch.restaurant %></td>
    <td><%= lunch.food %></td>
    <td><%= link_to 'Show', lunch %></td>
    <td><%= link_to 'Edit', edit_lunch_path(lunch) %></td>
    <td><%= link_to 'Destroy', lunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lunch', new_lunch_path %>

app/views/lunches/new.html.erb
<h1>New lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @lunch.date %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @lunch.restaurant %>
</p>

<p>
  <b>Food:</b>
  <%= @lunch.food %>
</p>


<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>